### ISSUE TITLE
Join science-build-rules and science-build-environment

### ISSUE THREAD

**Issue by simo-tuomisto** [AaltoScienceIT/science-build-rules#19]
There's no longer need to separate science-build-environment and science-build-rules. Instead science-build-environment should be placed into a subfolder of science-build-rules.

- [ ]  Bring science-build-environment into `build_environment` or similar.
- [ ] Update CI buildrule so that it will find the build environment.
- [ ]  Test the installation.
- [ ]  Join documentation of these new projects.

**Comment by rkdarst** [comment]
This way does it without fully rewriting history:
```
git remote add other_repo git://
git branch other-master other_repo/master
git checkout other-master
git mv   # move stuff into how you want it and how it is mergeable
...
git commit
# go back to master and merge
git checkout master
git merge other-master
```

**Comment by simo-tuomisto** [comment]
Closing this issue as we're already moving to a new builder.
