### ISSUE TITLE
fgci-centos7-*: Deciding on system packages

### ISSUE THREAD

**Issue by simo-tuomisto** [AaltoScienceIT/science-build-rules#2]
Current packages  that come from system image:

- autoconf: Image has autoconf-2.69-11.el7.noarch.
- automake: Image has automake-1.13.4-3.el7.noarch. Some package depend on automake@1.14:.
- libtool: Image has libtool-2.4.2-22.el7_3.x86_64. 
- m4: Image has m4-1.4.16-10.el7.x86_64.
- openssl: Image has openssl-devel-1.0.2k-16.el7_6.1.x86_64.
- slurm: Image has slurm-devel-17.11.5-1.el7.centos.x86_64.

**Comment by simo-tuomisto** [comment]
autoconf, automake and libtool did not work from /fake/path. Switched them back.

**Comment by jabl** [comment]
Do we have bison and flex?

**Comment by simo-tuomisto** [comment]
Closing this issue as we're already moving to a new builder.
